import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const employeeDepartments = [
  // Engineering & Science Departments
  { id: 1, value: "Computer Science and Engineering (CSE)" },
  { id: 2, value: "Industrial and Production Engineering (IPE)" },
  { id: 3, value: "Petroleum and Mining Engineering (PME)" },
  { id: 4, value: "Chemical Engineering (ChE)" },
  { id: 5, value: "Electrical and Electronic Engineering (EEE)" },
  { id: 6, value: "Biomedical Engineering (BME)" },
  { id: 7, value: "Textile Engineering (TE)" },
  { id: 8, value: "Microbiology (MB)" },
  { id: 9, value: "Fisheries and Marine Bioscience (FMB)" },
  { id: 10, value: "Genetic Engineering and Biotechnology (GEBT)" },
  { id: 11, value: "Pharmacy (PHAR)" },
  { id: 12, value: "Biochemistry and Molecular Biology (BMB)" },
  { id: 13, value: "Environmental Science and Technology (EST)" },
  { id: 14, value: "Nutrition and Food Technology (NFT)" },
  { id: 15, value: "Food Engineering (FE)" },
  { id: 16, value: "Climate and Disaster Management (CDM)" },
  { id: 17, value: "Physical Education and Sports Science (PESS)" },
  { id: 18, value: "Physiotherapy and Rehabilitation (PTR)" },
  { id: 19, value: "Nursing and Health Science (NHS)" },
  { id: 20, value: "English (ENG)" },
  { id: 21, value: "Physics (PHY)" },
  { id: 22, value: "Chemistry (CHEM)" },
  { id: 23, value: "Mathematics (MATH)" },
  { id: 24, value: "Applied Statistics and Data Science (ASDS)" },
  { id: 25, value: "Accounting and Information Systems (AIS)" },
  { id: 26, value: "Management (MGT)" },
  { id: 27, value: "Marketing (MKT)" },
  { id: 28, value: "Finance and Banking (FB)" },
  { id: 29, value: "Veterinary Medicine (DVM)" },

  // Faculties
  { id: 30, value: "Faculty of Engineering & Technology" },
  { id: 31, value: "Faculty of Applied Science & Technology" },
  { id: 32, value: "Faculty of Biological Science & Technology" },
  { id: 33, value: "Faculty of Health Science" },
  { id: 34, value: "Faculty of Science" },
  { id: 35, value: "Faculty of Veterinary Medicine" },
  { id: 36, value: "Faculty of Arts and Social Science" },
  { id: 37, value: "Faculty of Business Studies" },

  // Offices, Halls, and Institutes
  { id: 38, value: "Office of the Vice Chancellor" },
  { id: 39, value: "Office of the Treasurer" },
  { id: 40, value: "Office of the Registrar" },
  { id: 41, value: "Office of the ICT Cell" },
  { id: 42, value: "Office of the Librarian" },
  { id: 43, value: "Shaheed Mashiur Rahman Hall" },
  { id: 44, value: "Taposhi Rabeya Hall" },
  { id: 45, value: "Munshi Mohammad Meherullah Hall" },
  { id: 46, value: "Beerprotik Taramon Bibi Hall" },
  { id: 47, value: "Office of the Proctor" },
  { id: 48, value: "Office of the Student Counseling and Guidance" },
  { id: 49, value: "Office of the Director of Accounts" },
  { id: 50, value: "Office of the Director of Planning, Development & Works" },
  { id: 51, value: "Office of the Controller of Examinations" },
  { id: 52, value: "Office of the Chief Engineer" },
  { id: 53, value: "Office of the Chief Medical Officer" },
  { id: 54, value: "Institute for Higher Education and Research (IHER)" },
  { id: 55, value: "Office of the Research Cell" },
  { id: 56, value: "Institutional Quality Assurance Cell (IQAC)" },
  { id: 57, value: "CSIRL" },
  { id: 58, value: "Genome Centre" },
  { id: 59, value: "International Service Center (ISC)" },
  { id: 60, value: "Office of the Physical Education" },
  { id: 61, value: "Office of the Transport Administrator" },
  { id: 62, value: "Audit Cell" },
  { id: 63, value: "Public relation branch (Registrar Office)" },
  { id: 64, value: "Teachers and Students Centre (TSC)" },
  { id: 65, value: "Cyber Centre" },
  { id: 66, value: "Modern Fish Hatchery and Wet Lab" },
];
